version: "3.8"

services:

  nginx:
    image: nginx:1.19-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx

  
  frontend:
    image: frontend
    build: ./example-frontend
 #  Ports not exposed
 #   ports:
 #     - 5001:5000
    container_name: frontend

  backend:
    image: backend
    build: ./example-backend
#   Ports not exposed
#    ports:
#      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost #This line was added comapared exercise 2.9
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=example
      - POSTGRESS_DATABASE=db
    depends_on:
      - db
      - redis
    container_name: backend

  redis:
    image: redis
    container_name: redis

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    volumes:
      - ./data:/var/lib/postgresql/data
    container_name: db
