version: "3.8"

services:
  
  frontend:
    image: frontend
    ports:
      - 5001:5000
    container_name: frontend

  backend:
    image: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    container_name: backend

  redis:
    image: redis
    container_name: redis
